# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/mag_func_test.dir/mag_func_test.c.o: mag_func_test.c
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: ran1/ran1.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: alomax_matrix/alomax_matrix.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: alomax_matrix/alomax_matrix_svd.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: geometry/geometry.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/GridLib.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/GridMemLib.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/NLLocLib.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/calc_crust_corr.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/geo.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/map_project.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/otime_limit.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/phaseloclist.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/util.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: include/velmod.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: matrix_statistics/matrix_statistics.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: octtree/octtree.h
CMakeFiles/mag_func_test.dir/mag_func_test.c.o: ran1/ran1.h

