# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# compile C with /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
C_FLAGS = -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14   -DNO_IEEE_PROTOCOL

C_DEFINES = 

C_INCLUDES = -I/Users/anthony/soft/NLLoc/src/include -I/Users/anthony/soft/NLLoc/src/alomax_matrix -I/Users/anthony/soft/NLLoc/src/geometry -I/Users/anthony/soft/NLLoc/src/matrix_statistics -I/Users/anthony/soft/NLLoc/src/ran1 -I/Users/anthony/soft/NLLoc/src/octtree -I/Users/anthony/soft/NLLoc/src 

