# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/grid2scat.dir/grid2scat.c.o: grid2scat.c
CMakeFiles/grid2scat.dir/grid2scat.c.o: alomax_matrix/alomax_matrix.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: alomax_matrix/alomax_matrix_svd.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: geometry/geometry.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: include/GridLib.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: include/geo.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: include/map_project.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: include/util.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: matrix_statistics/matrix_statistics.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: octtree/octtree.h
CMakeFiles/grid2scat.dir/grid2scat.c.o: ran1/ran1.h

