# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/anthony/soft/NLLoc/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/anthony/soft/NLLoc/src

# Include any dependencies generated for this target.
include CMakeFiles/GRID_LIB_OBJS.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/GRID_LIB_OBJS.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/GRID_LIB_OBJS.dir/flags.make

CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: GridLib.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o   -c /Users/anthony/soft/NLLoc/src/GridLib.c

CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/GridLib.c > CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.i

CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/GridLib.c -o CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.s

CMakeFiles/GRID_LIB_OBJS.dir/util.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/util.c.o: util.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/util.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/util.c.o   -c /Users/anthony/soft/NLLoc/src/util.c

CMakeFiles/GRID_LIB_OBJS.dir/util.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/util.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/util.c > CMakeFiles/GRID_LIB_OBJS.dir/util.c.i

CMakeFiles/GRID_LIB_OBJS.dir/util.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/util.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/util.c -o CMakeFiles/GRID_LIB_OBJS.dir/util.c.s

CMakeFiles/GRID_LIB_OBJS.dir/geo.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/geo.c.o: geo.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/geo.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/geo.c.o   -c /Users/anthony/soft/NLLoc/src/geo.c

CMakeFiles/GRID_LIB_OBJS.dir/geo.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/geo.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/geo.c > CMakeFiles/GRID_LIB_OBJS.dir/geo.c.i

CMakeFiles/GRID_LIB_OBJS.dir/geo.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/geo.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/geo.c -o CMakeFiles/GRID_LIB_OBJS.dir/geo.c.s

CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o: octtree/octtree.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o   -c /Users/anthony/soft/NLLoc/src/octtree/octtree.c

CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/octtree/octtree.c > CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.i

CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/octtree/octtree.c -o CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.s

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o: alomax_matrix/alomax_matrix.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o   -c /Users/anthony/soft/NLLoc/src/alomax_matrix/alomax_matrix.c

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/alomax_matrix/alomax_matrix.c > CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.i

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/alomax_matrix/alomax_matrix.c -o CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.s

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.o: alomax_matrix/eigv.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.o   -c /Users/anthony/soft/NLLoc/src/alomax_matrix/eigv.c

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/alomax_matrix/eigv.c > CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.i

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/alomax_matrix/eigv.c -o CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.s

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o: alomax_matrix/alomax_matrix_svd.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o   -c /Users/anthony/soft/NLLoc/src/alomax_matrix/alomax_matrix_svd.c

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/alomax_matrix/alomax_matrix_svd.c > CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.i

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/alomax_matrix/alomax_matrix_svd.c -o CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.s

CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o: matrix_statistics/matrix_statistics.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o   -c /Users/anthony/soft/NLLoc/src/matrix_statistics/matrix_statistics.c

CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/matrix_statistics/matrix_statistics.c > CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.i

CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/matrix_statistics/matrix_statistics.c -o CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.s

CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.o: vector/vector.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.o   -c /Users/anthony/soft/NLLoc/src/vector/vector.c

CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/vector/vector.c > CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.i

CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/vector/vector.c -o CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.s

CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.o: ran1/ran1.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.o   -c /Users/anthony/soft/NLLoc/src/ran1/ran1.c

CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/ran1/ran1.c > CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.i

CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/ran1/ran1.c -o CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.s

CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.o: CMakeFiles/GRID_LIB_OBJS.dir/flags.make
CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.o: map_project.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/anthony/soft/NLLoc/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building C object CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.o"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.o   -c /Users/anthony/soft/NLLoc/src/map_project.c

CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.i"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /Users/anthony/soft/NLLoc/src/map_project.c > CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.i

CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.s"
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /Users/anthony/soft/NLLoc/src/map_project.c -o CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.s

GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/util.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/geo.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.o
GRID_LIB_OBJS: CMakeFiles/GRID_LIB_OBJS.dir/build.make

.PHONY : GRID_LIB_OBJS

# Rule to build all files generated by this target.
CMakeFiles/GRID_LIB_OBJS.dir/build: GRID_LIB_OBJS

.PHONY : CMakeFiles/GRID_LIB_OBJS.dir/build

CMakeFiles/GRID_LIB_OBJS.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/GRID_LIB_OBJS.dir/cmake_clean.cmake
.PHONY : CMakeFiles/GRID_LIB_OBJS.dir/clean

CMakeFiles/GRID_LIB_OBJS.dir/depend:
	cd /Users/anthony/soft/NLLoc/src && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/anthony/soft/NLLoc/src /Users/anthony/soft/NLLoc/src /Users/anthony/soft/NLLoc/src /Users/anthony/soft/NLLoc/src /Users/anthony/soft/NLLoc/src/CMakeFiles/GRID_LIB_OBJS.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/GRID_LIB_OBJS.dir/depend

