# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: GridLib.c
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: alomax_matrix/alomax_matrix.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: alomax_matrix/alomax_matrix_svd.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: geometry/geometry.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: include/GridLib.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: include/geo.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: include/map_project.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: include/util.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: matrix_statistics/matrix_statistics.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: octtree/octtree.h
CMakeFiles/GRID_LIB_OBJS.dir/GridLib.c.o: ran1/ran1.h

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o: alomax_matrix/alomax_matrix.c
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o: alomax_matrix/alomax_matrix.h
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o: alomax_matrix/alomax_matrix_svd.h
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix.c.o: alomax_matrix/eigv.h

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o: alomax_matrix/alomax_matrix.h
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o: alomax_matrix/alomax_matrix_svd.c
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/alomax_matrix_svd.c.o: alomax_matrix/alomax_matrix_svd.h

CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.o: alomax_matrix/eigv.c
CMakeFiles/GRID_LIB_OBJS.dir/alomax_matrix/eigv.c.o: alomax_matrix/eigv.h

CMakeFiles/GRID_LIB_OBJS.dir/geo.c.o: geo.c
CMakeFiles/GRID_LIB_OBJS.dir/geo.c.o: include/geo.h

CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.o: map_project.c
CMakeFiles/GRID_LIB_OBJS.dir/map_project.c.o: include/map_project.h

CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o: alomax_matrix/alomax_matrix.h
CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o: geometry/geometry.h
CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o: matrix_statistics/matrix_statistics.c
CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o: matrix_statistics/matrix_statistics.h
CMakeFiles/GRID_LIB_OBJS.dir/matrix_statistics/matrix_statistics.c.o: vector/vector.h

CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o: octtree/geometry.h
CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o: octtree/octtree.c
CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o: octtree/octtree.h
CMakeFiles/GRID_LIB_OBJS.dir/octtree/octtree.c.o: octtree/ran1.h

CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.o: ran1/ran1.c
CMakeFiles/GRID_LIB_OBJS.dir/ran1/ran1.c.o: ran1/ran1.h

CMakeFiles/GRID_LIB_OBJS.dir/util.c.o: util.c
CMakeFiles/GRID_LIB_OBJS.dir/util.c.o: include/util.h

CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.o: vector/vector.c
CMakeFiles/GRID_LIB_OBJS.dir/vector/vector.c.o: vector/vector.h

