# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: calc_crust_corr.c
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: alomax_matrix/alomax_matrix.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: alomax_matrix/alomax_matrix_svd.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: geometry/geometry.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/GridLib.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/calc_crust_corr.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/crust_corr_model.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/crust_type.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/crust_type_key.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/geo.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/map_project.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: include/util.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: matrix_statistics/matrix_statistics.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: octtree/octtree.h
CMakeFiles/calc_crust_corr.dir/calc_crust_corr.c.o: ran1/ran1.h

