# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

CMakeFiles/velmod.dir/velmod.c.o: velmod.c
CMakeFiles/velmod.dir/velmod.c.o: include/util.h
CMakeFiles/velmod.dir/velmod.c.o: include/velmod.h

